<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Generateur de class PDO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- jvectormap -->
    <link href="views/assets/libs/jqvmap/jqvmap.min.css" rel="stylesheet" />

    <!-- DataTables -->
    <link href="views/assets/libs/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="views/assets/libs/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />

    <!-- App css -->
    <link href="views/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="views/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="views/assets/css/app.min.css" rel="stylesheet" type="text/css" />

</head>

<body class="authentication-bg authentication-bg-pattern d-flex align-items-center">

    <div class="home-btn d-none d-sm-block">
        <a href="index.html"><i class="fas fa-home h2 text-white"></i></a>
    </div>

    <div class="account-pages w-100 mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card">

                        <div class="card-body p-4">

                            <div class="text-center mb-4">
                                <h3>Générateur de classe PDO en PHP test !</h3>
                            </div>
                            <form method="POST" class="pt-2">

                                <div class="form-group mb-3">
                                    <label for="inputHost">Host :</label>
                                    <input name="host" class="form-control" type="text" id="host" required="" value="localhost">
                                </div>

                                <div class="form-group mb-3">
                                    <label for="inputPort">Port :</label>
                                    <input name="port" class="form-control" type="text" required="" id="port" value="3306">
                                </div>

                                <div class="form-group mb-3">
                                    <label for="inputUtilisateur">Utilisateur :</label>
                                    <input name="utilisateur" class="form-control" type="text" required="" id="utilisateur" value="root">
                                </div>

                                <div class="form-group mb-3">
                                    <label for="inputMDP">Mot de Passe :</label>
                                    <input name="mdp" class="form-control" type="password" id="mdp" value="">
                                </div>

                                <div class="form-group mb-0 text-center">
                                    <button class="btn btn-success btn-block" name="btnValider" id="btnValider" type="submit">Valider</button>
                                </div>

                            </form>


                            <!-- end row -->

                        </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->

    <!-- Vendor js -->
    <script src="views/assets/js/vendor.min.js"></script>

    <!-- App js -->
    <script src="views/assets/js/app.min.js"></script>
    <script src="views/assets/js/index.js"></script>

</body>

</html>