<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Greeva - Responsive Bootstrap 4 Admin Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- jvectormap -->
    <link href="assets/libs/jqvmap/jqvmap.min.css" rel="stylesheet" />

    <!-- DataTables -->
    <link href="assets/libs/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/libs/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />

    <!-- App css -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/app.min.css" rel="stylesheet" type="text/css" />

</head>

<body class="authentication-bg authentication-bg-pattern d-flex align-items-center">

    <div class="home-btn d-none d-sm-block">
        <a href="index.html"><i class="fas fa-home h2 text-white"></i></a>
    </div>

    <div class="account-pages w-100 mt-5 mb-5">
        <div class="container">
            <div class="justify-content-center">
                <div class="card">

                    <div class="card-body p-4 text-center justify-content-center">

                        <div class="text-center mb-4">
                            <h3>Listes des bases de données !</h3>
                        </div>
                        <div id="formAll" class="text-center mb-4">
                            <form action="" method="POST">
                                <select class="form-select" aria-label="multiple select example" name="listeBD" id="listeBD" multiple size="">
                                </select>
                                <div id="divCreateDb" class="form-group mb-3">
                                    <label id="lblCreateDb" for="btnCreateDb" class="text-primary">Voulez vous créer le fichier Database.php de la base sélectionnée?</label>
                                    <br />
                                    <button name="btnCreateDb" class="btn btn-info" type="button" id="btnCreateDb">Oui</button>
                                    <button name="btnNoCreateDb" class="btn btn-danger" type="button" id="btnNoCreateDb">Non</button>
                                    <br />
                                </div>
                                <button type="button" name="btnChoisir" id="btnChoisir" class="btn btn-success"> Choisir </button>
                                <select name="listeTable" id="listeTable" multiple="multiple" size="" hidden>
                                </select>
                                <div>
                                    <input type="radio" id="chkMetier" name="radio" value="metier" hidden><label class="text-primary" id="lblMetier" name="lblMetier" for="chkMetier" hidden>Classe métier (DTO)</label>
                                    <br>
                                    <input type="radio" id="chkDAO" name="radio" value="DAO" hidden><label class="text-primary" id="lblDAO" name="lblDAO" for="chkDAO" hidden>Classe DAO</label>
                                </div>
                                <button type="button" name="btnValider" id="btnValider" class="btn btn-success" hidden> Valider </button>
                                <br>
                                <textarea id="pMessage" name="pMessage" class="w-25" style="height: 300px;" hidden></textarea>
                                <br />
                                <br />
                                <label id="lblMessage" class="text-primary" hidden> Souhaitez-vous crée le fichier ? </label>
                                <button type="button" id="btnOui" name="btnOui" class="btn btn-success" hidden> Oui </button>
                                <button type="button" id="btnNon" name="btnNon" class="btn btn-danger" hidden> Non </button>
                                <br />
                                <label class="text-primary" id="lblMessageValidation" hidden></label>
                                <button name="btnRecupFile" class="btn btn-info" type="button" id="btnRecupFile">Oui</button>
                                <button name="btnNoRecupFile" class="btn btn-info" type="button" id="btnNoRecupFile">Non</button>
                            </form>
                        </div>

                        <!-- A faire plus tard
                            Permettre de pouvoir telecharger le ou les fichiers crées
                            soit en js voir JSZip librairie pour faire des zip
                            soit en php ZipArchives librairie pour compresser des fichiers
                            Et apres gerer les telechargement
                        -->
                        <!-- <div id="recupFile">
                            <a id="aRecupFile" href="../dossierClassMetier/archive" download>Recuperation du fichier !</a>
                        </div> -->


                        <!-- end row -->

                    </div> <!-- end card-body -->
                </div>
                <!-- end card -->

            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->

    <!-- Vendor js -->
    <script src="assets/js/vendor.min.js"></script>

    <!-- App js -->
    <script src="assets/js/app.min.js"></script>
    <script src="assets/js/showBD.js"></script>

</body>

</html>